# Generated by Django 4.2.7 on 2023-12-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='view',
        ),
    ]
